### ISSUE TITLE
2019-06-25 version provision

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__Deck_and_Card_Info_during_review#2]
Hello. Do you mind providing the 2019-06-25 version as a release until a fix for Progress Bar is released? I updated from the addon manager and so didn't see the warning.

**Comment by ijgnd** [comment]
I can upload the old version. 

But there are only minimal changes between the latest version and the version from 2019-06-25. So the new version works as well as the old one with the progress bar add-on and the old version also doesn't work fully with the "Progress Bar" add-on, see the first review from January 2019 on [ankiweb](https://ankiweb.net/shared/info/673114053). 

The update of the add-on was only an ocassion to update the description. The limitation has nothing to do with the update. I also noted that the add-ons are not compatible so that you can't have both enabled at the same time. 

To remove this limitation: edit the file `meta.json` in the add-on folder of my add-on and remove and remove the progress bar add-on id from the list of incompatible add-ons so that it looks like this `"conflicts": ["4241959", "1008566916", "2179254157"]` afterwards. Then restart anki and you should be able to enable both at the same time.

**Comment by ghost** [comment]
Thank you for pointing out the fix. Works perfectly.
