### ISSUE TITLE
Version 2.1.20 (47a1bf8b) - Night mode broken

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ijgnd/anki__Deck_and_Card_Info_during_review#5]
On my macbook pro night mode doesnt work but it does work on my iMac at home.

**Comment by ijgnd** [comment]
I would update Anki on your macbook to the latest versions and disable all other add-ons and restart and see if it works then. 

If not I have no idea since I have no Mac. 

If it works then it might be an add-on conflict. I would enable half of the other add-ons and try again. If everything works enable half of the remaining half and so on so that within a few steps you identify the conflict.

&nbsp;

Maybe also share a screenshot and from the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text. Maybe this will give me an idea.
